export const LOAD_MENU = 'LOAD_MENU'
export const LOAD_ABOUT = 'LOAD_ABOUT'
export const LOAD_AROM_GROUP = 'LOAD_AROM_GROUP'
export const LOAD_CONTACTS = 'LOAD_CONTACTS'
export const LOAD_NEWS = 'LOAD_NEWS'
export const TOGGLE_OPEN_NEWS = 'TOGGLE_OPEN_NEWS'
export const LOAD_DISTRIBS = 'LOAD_DISTRIBS'
export const LOAD_FULL_ASSORTIMENT = 'LOAD_FULL_ASSORTIMENT'
export const SEND_FORM = 'SEND_FORM'
export const LOAD_VENDORS = 'LOAD_VENDORS'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'
